version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - php
    restart: on-failure

  php:
    image: php:8.0-fpm
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: xfree86
      MYSQL_DATABASE: app_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: xfree86
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  mariadb_data:
